name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-2019]
        java: [6, 7, 7.0.121, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
        java-package: jdk
    - name: Java version
      run: java -version && javac -version
    - name: Build
      run: ./mvnw verify
